# Generated by Django 5.0.4 on 2024-04-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_article_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="date",
        ),
        migrations.RemoveField(
            model_name="article",
            name="description",
        ),
    ]
