# Generated by Django 5.0.4 on 2024-04-30 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_remove_article_date_remove_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Published Date"
            ),
        ),
    ]
